= Resource Filtering Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-resource-filtering/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-resource-filtering/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===

== Description

The resource filtering is designed to filter rest resources. By applying this filter you can restrict or allow access to
 a specific resource determined by a path and a method (or an array of methods).

This policy is mainly used in a <<plan-configuration, plan configuration>> to allow access to
subscribers to specific resources only.

A typical usage would be to allow access to all paths (/**) but in read-only mode (GET method).

WARNING: You can't apply both resource whitelist and resource blacklist in the same time. Whitelisting takes precedence over blacklisting.


== Configuration

|===
|Property |Required |Description |Type| Default

.^|whitelist
^.^|-
|List of allowed resources.
^.^|array of <<gravitee-policy-resource-filtering-resource, `resources`>>
^.^|-

.^|blacklist
^.^|-
|List of restricted resources.
^.^|array of <<gravitee-policy-resource-filtering-resource, `resources`>>
^.^|-

|===

[[gravitee-policy-resource-filtering-resource]]
A `Resource` is defined as follow:
|===
|Property |Required |Description |Type| Default

.^|pattern
^.^|X
|An <<gravitee-policy-resource-filtering-ant, Ant-style path patterns>> (http://ant.apache.org/[Apache Ant]).
^.^|string
^.^|-

.^|methods
^.^|-
|List of HTTP methods for which filter is applied.
^.^|array of HTTP methods
^.^|All HTTP methods

|===

[source, json]
.Configuration example
"resource-filtering" : {
    "whitelist":[
        {
            "pattern":"/**",
            "methods": ["GET"]
        }
    ]
}

[[gravitee-policy-resource-filtering-ant]]
=== Ant style path pattern
The mapping matches URLs using the following rules:

* `?` matches one character
* `*` matches zero or more characters
* `**` matches zero or more directories in a path

== Errors

=== Default Errors
|===
|Code |Message

.^| ```403```
| Access to the resource is forbidden according to resource-filtering rules.

|===

=== Override Errors
If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys send by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|RESOURCE_FILTERING_FORBIDDEN
^.^|path - method

|===